export const SETTINGS = {
  SET_DARK_MODE: "SET_DARK_MODE",
  SET_IS_METRIC: "SET_IS_METRIC",
};

export const WEATHER = {
  GET_CURRENT_CONDITIONS: "GET_CURRENT_CONDITIONS",
  GET_LOCAL_CURRENT_CONDITIONS: "GET_LOCAL_CURRENT_CONDITIONS",
  SET_CURRENT_CONDITIONS: "SET_CURRENT_CONDITIONS",
  SET_FIVE_DAY_FORECAST: "SET_FIVE_DAY_FORECAST",
  SET_FAVORITES: "SET_FAVORITES",
  ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
  REMOVE_FROM_FAVORITES: "REMOVE_FROM_FAVORITES",
  GET_SEARCH_RESULTS: "GET_SEARCH_RESULTS",
  SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",
  SET_ERROR: "SET_ERROR",
};
